// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/common.proto
// 
package enums

type Code int

const (

	// CodeSuccess
	// @msg:成功
	CodeSuccess Code = 0

	// CodeParseReqErr
	// @msg:参数解析失败
	CodeParseReqErr Code = 10400

	// CodeUnauthorized
	// @msg:未登录
	CodeUnauthorized Code = 10401

	// CodeForbidden
	// @msg:没有权限
	CodeForbidden Code = 100403

	// CodeNotFound
	// @msg:找不到
	CodeNotFound Code = 100404

	// CodeBizErr
	// @msg:业务错误m,
	CodeBizErr Code = 10201

	// CodeInternalErr
	// @msg:内部错误
	CodeInternalErr Code = 10500
	CodeUnknown     Code = -1000
)

func (item Code) String() string {
	switch item {
	case CodeSuccess:
		return "Success"
	case CodeParseReqErr:
		return "ParseReqErr"
	case CodeUnauthorized:
		return "Unauthorized"
	case CodeForbidden:
		return "Forbidden"
	case CodeNotFound:
		return "NotFound"
	case CodeBizErr:
		return "BizErr"
	case CodeInternalErr:
		return "InternalErr"
	default:
		return "Unknown"
	}
}

func (item Code) Message() string {
	switch item {
	case CodeSuccess:
		return "成功"
	case CodeParseReqErr:
		return "参数解析失败"
	case CodeUnauthorized:
		return "未登录"
	case CodeForbidden:
		return "没有权限"
	case CodeNotFound:
		return "找不到"
	case CodeBizErr:
		return "业务错误m,"
	case CodeInternalErr:
		return "内部错误"
	default:
		return "Unknown"
	}
}

func ParseCodeFromString(msg string) Code {
	switch msg {
	case "Success":
		return CodeSuccess
	case "ParseReqErr":
		return CodeParseReqErr
	case "Unauthorized":
		return CodeUnauthorized
	case "Forbidden":
		return CodeForbidden
	case "NotFound":
		return CodeNotFound
	case "BizErr":
		return CodeBizErr
	case "InternalErr":
		return CodeInternalErr
	default:
		return CodeUnknown
	}
}

func CodeValueEnum() map[string]any {
	return map[string]any{
		"Success":      "成功",
		"ParseReqErr":  "参数解析失败",
		"Unauthorized": "未登录",
		"Forbidden":    "没有权限",
		"NotFound":     "找不到",
		"BizErr":       "业务错误m,",
		"InternalErr":  "内部错误",
	}
}
