// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

type ActionType int

const (

	// ActionTypeshow
	// @msg:展示
	ActionTypeshow ActionType = 0

	// ActionTypeedit
	// @msg:编辑
	ActionTypeedit ActionType = 1

	// ActionTypedelete
	// @msg:删除
	ActionTypedelete ActionType = 2

	// ActionTypebatchDelete
	// @msg:批量删除
	ActionTypebatchDelete ActionType = 3

	// ActionTypeexport
	// @msg:导出
	ActionTypeexport ActionType = 4

	// ActionTypecreate
	// @msg:创建
	ActionTypecreate  ActionType = 5
	ActionTypeUnknown ActionType = -1000
)

func (item ActionType) String() string {
	switch item {
	case ActionTypeshow:
		return "show"
	case ActionTypeedit:
		return "edit"
	case ActionTypedelete:
		return "delete"
	case ActionTypebatchDelete:
		return "batchDelete"
	case ActionTypeexport:
		return "export"
	case ActionTypecreate:
		return "create"
	default:
		return "Unknown"
	}
}

func (item ActionType) Message() string {
	switch item {
	case ActionTypeshow:
		return "展示"
	case ActionTypeedit:
		return "编辑"
	case ActionTypedelete:
		return "删除"
	case ActionTypebatchDelete:
		return "批量删除"
	case ActionTypeexport:
		return "导出"
	case ActionTypecreate:
		return "创建"
	default:
		return "Unknown"
	}
}

func ParseActionTypeFromString(msg string) ActionType {
	switch msg {
	case "show":
		return ActionTypeshow
	case "edit":
		return ActionTypeedit
	case "delete":
		return ActionTypedelete
	case "batchDelete":
		return ActionTypebatchDelete
	case "export":
		return ActionTypeexport
	case "create":
		return ActionTypecreate
	default:
		return ActionTypeUnknown
	}
}

func ActionTypeValueEnum() map[string]any {
	return map[string]any{
		"show":        "展示",
		"edit":        "编辑",
		"delete":      "删除",
		"batchDelete": "批量删除",
		"export":      "导出",
		"create":      "创建",
	}
}
