// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

type AdminSmsType int

const (

	// AdminSmsTypelogin
	// @msg:登录
	AdminSmsTypelogin AdminSmsType = 0

	// AdminSmsTypereset
	// @msg:重置密码
	AdminSmsTypereset   AdminSmsType = 1
	AdminSmsTypeUnknown AdminSmsType = -1000
)

func (item AdminSmsType) String() string {
	switch item {
	case AdminSmsTypelogin:
		return "login"
	case AdminSmsTypereset:
		return "reset"
	default:
		return "Unknown"
	}
}

func (item AdminSmsType) Message() string {
	switch item {
	case AdminSmsTypelogin:
		return "登录"
	case AdminSmsTypereset:
		return "重置密码"
	default:
		return "Unknown"
	}
}

func ParseAdminSmsTypeFromString(msg string) AdminSmsType {
	switch msg {
	case "login":
		return AdminSmsTypelogin
	case "reset":
		return AdminSmsTypereset
	default:
		return AdminSmsTypeUnknown
	}
}

func AdminSmsTypeValueEnum() map[string]any {
	return map[string]any{
		"login": "登录",
		"reset": "重置密码",
	}
}
