// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

type AdminRole int

const (

	// AdminRolesuper_admin
	// @msg:超级管理员
	AdminRolesuper_admin AdminRole = 0

	// AdminRoleoperator
	// @msg:运营管理员
	AdminRoleoperator AdminRole = 1

	// AdminRoleviewer
	// @msg:查看者
	AdminRoleviewer  AdminRole = 2
	AdminRoleUnknown AdminRole = -1000
)

func (item AdminRole) String() string {
	switch item {
	case AdminRolesuper_admin:
		return "super_admin"
	case AdminRoleoperator:
		return "operator"
	case AdminRoleviewer:
		return "viewer"
	default:
		return "Unknown"
	}
}

func (item AdminRole) Message() string {
	switch item {
	case AdminRolesuper_admin:
		return "超级管理员"
	case AdminRoleoperator:
		return "运营管理员"
	case AdminRoleviewer:
		return "查看者"
	default:
		return "Unknown"
	}
}

func ParseAdminRoleFromString(msg string) AdminRole {
	switch msg {
	case "super_admin":
		return AdminRolesuper_admin
	case "operator":
		return AdminRoleoperator
	case "viewer":
		return AdminRoleviewer
	default:
		return AdminRoleUnknown
	}
}

func AdminRoleValueEnum() map[string]any {
	return map[string]any{
		"super_admin": "超级管理员",
		"operator":    "运营管理员",
		"viewer":      "查看者",
	}
}
