// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

type ColumnValueType int

const (

	// ColumnValueTypetext
	// @msg:文本
	ColumnValueTypetext ColumnValueType = 0

	// ColumnValueTypedateTime
	// @msg:日期时间
	ColumnValueTypedateTime ColumnValueType = 1

	// ColumnValueTypeavatar
	// @msg:头像
	ColumnValueTypeavatar ColumnValueType = 2

	// ColumnValueTypeurl
	// @msg:链接
	ColumnValueTypeurl ColumnValueType = 3

	// ColumnValueTypeimage
	// @msg:图片
	ColumnValueTypeimage ColumnValueType = 4

	// ColumnValueTypenumber
	// @msg:数字
	ColumnValueTypenumber ColumnValueType = 5

	// ColumnValueTypeselect
	// @msg:选择
	ColumnValueTypeselect  ColumnValueType = 6
	ColumnValueTypeUnknown ColumnValueType = -1000
)

func (item ColumnValueType) String() string {
	switch item {
	case ColumnValueTypetext:
		return "text"
	case ColumnValueTypedateTime:
		return "dateTime"
	case ColumnValueTypeavatar:
		return "avatar"
	case ColumnValueTypeurl:
		return "url"
	case ColumnValueTypeimage:
		return "image"
	case ColumnValueTypenumber:
		return "number"
	case ColumnValueTypeselect:
		return "select"
	default:
		return "Unknown"
	}
}

func (item ColumnValueType) Message() string {
	switch item {
	case ColumnValueTypetext:
		return "文本"
	case ColumnValueTypedateTime:
		return "日期时间"
	case ColumnValueTypeavatar:
		return "头像"
	case ColumnValueTypeurl:
		return "链接"
	case ColumnValueTypeimage:
		return "图片"
	case ColumnValueTypenumber:
		return "数字"
	case ColumnValueTypeselect:
		return "选择"
	default:
		return "Unknown"
	}
}

func ParseColumnValueTypeFromString(msg string) ColumnValueType {
	switch msg {
	case "text":
		return ColumnValueTypetext
	case "dateTime":
		return ColumnValueTypedateTime
	case "avatar":
		return ColumnValueTypeavatar
	case "url":
		return ColumnValueTypeurl
	case "image":
		return ColumnValueTypeimage
	case "number":
		return ColumnValueTypenumber
	case "select":
		return ColumnValueTypeselect
	default:
		return ColumnValueTypeUnknown
	}
}

func ColumnValueTypeValueEnum() map[string]any {
	return map[string]any{
		"text":     "文本",
		"dateTime": "日期时间",
		"avatar":   "头像",
		"url":      "链接",
		"image":    "图片",
		"number":   "数字",
		"select":   "选择",
	}
}
