// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/export.proto
// 
package admin

type ExportStatus int

const (

	// ExportStatuspending
	// @msg:排队中
	ExportStatuspending ExportStatus = 0

	// ExportStatusprocessing
	// @msg:处理中
	ExportStatusprocessing ExportStatus = 1

	// ExportStatuscompleted
	// @msg:已完成
	ExportStatuscompleted ExportStatus = 2

	// ExportStatusfailed
	// @msg:处理失败
	ExportStatusfailed  ExportStatus = 3
	ExportStatusUnknown ExportStatus = -1000
)

func (item ExportStatus) String() string {
	switch item {
	case ExportStatuspending:
		return "pending"
	case ExportStatusprocessing:
		return "processing"
	case ExportStatuscompleted:
		return "completed"
	case ExportStatusfailed:
		return "failed"
	default:
		return "Unknown"
	}
}

func (item ExportStatus) Message() string {
	switch item {
	case ExportStatuspending:
		return "排队中"
	case ExportStatusprocessing:
		return "处理中"
	case ExportStatuscompleted:
		return "已完成"
	case ExportStatusfailed:
		return "处理失败"
	default:
		return "Unknown"
	}
}

func ParseExportStatusFromString(msg string) ExportStatus {
	switch msg {
	case "pending":
		return ExportStatuspending
	case "processing":
		return ExportStatusprocessing
	case "completed":
		return ExportStatuscompleted
	case "failed":
		return ExportStatusfailed
	default:
		return ExportStatusUnknown
	}
}

func ExportStatusValueEnum() map[string]any {
	return map[string]any{
		"pending":    "排队中",
		"processing": "处理中",
		"completed":  "已完成",
		"failed":     "处理失败",
	}
}
