// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

type LoginMethod int

const (

	// LoginMethodpassword
	// @msg:密码登录
	LoginMethodpassword LoginMethod = 0

	// LoginMethodsms
	// @msg:短信登录
	LoginMethodsms     LoginMethod = 1
	LoginMethodUnknown LoginMethod = -1000
)

func (item LoginMethod) String() string {
	switch item {
	case LoginMethodpassword:
		return "password"
	case LoginMethodsms:
		return "sms"
	default:
		return "Unknown"
	}
}

func (item LoginMethod) Message() string {
	switch item {
	case LoginMethodpassword:
		return "密码登录"
	case LoginMethodsms:
		return "短信登录"
	default:
		return "Unknown"
	}
}

func ParseLoginMethodFromString(msg string) LoginMethod {
	switch msg {
	case "password":
		return LoginMethodpassword
	case "sms":
		return LoginMethodsms
	default:
		return LoginMethodUnknown
	}
}

func LoginMethodValueEnum() map[string]any {
	return map[string]any{
		"password": "密码登录",
		"sms":      "短信登录",
	}
}
