// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

type QueryOperator int

const (

	// QueryOperatoreq
	// @msg:等于
	QueryOperatoreq QueryOperator = 0

	// QueryOperatorlike
	// @msg:模糊匹配
	QueryOperatorlike QueryOperator = 1

	// QueryOperatorgt
	// @msg:大于
	QueryOperatorgt QueryOperator = 2

	// QueryOperatorlt
	// @msg:小于
	QueryOperatorlt QueryOperator = 3

	// QueryOperatorin
	// @msg:包含
	QueryOperatorin      QueryOperator = 4
	QueryOperatorUnknown QueryOperator = -1000
)

func (item QueryOperator) String() string {
	switch item {
	case QueryOperatoreq:
		return "eq"
	case QueryOperatorlike:
		return "like"
	case QueryOperatorgt:
		return "gt"
	case QueryOperatorlt:
		return "lt"
	case QueryOperatorin:
		return "in"
	default:
		return "Unknown"
	}
}

func (item QueryOperator) Message() string {
	switch item {
	case QueryOperatoreq:
		return "等于"
	case QueryOperatorlike:
		return "模糊匹配"
	case QueryOperatorgt:
		return "大于"
	case QueryOperatorlt:
		return "小于"
	case QueryOperatorin:
		return "包含"
	default:
		return "Unknown"
	}
}

func ParseQueryOperatorFromString(msg string) QueryOperator {
	switch msg {
	case "eq":
		return QueryOperatoreq
	case "like":
		return QueryOperatorlike
	case "gt":
		return QueryOperatorgt
	case "lt":
		return QueryOperatorlt
	case "in":
		return QueryOperatorin
	default:
		return QueryOperatorUnknown
	}
}

func QueryOperatorValueEnum() map[string]any {
	return map[string]any{
		"eq":   "等于",
		"like": "模糊匹配",
		"gt":   "大于",
		"lt":   "小于",
		"in":   "包含",
	}
}
