// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

type SortOrder int

const (

	// SortOrderasc
	// @msg:升序
	SortOrderasc SortOrder = 0

	// SortOrderdesc
	// @msg:降序
	SortOrderdesc    SortOrder = 1
	SortOrderUnknown SortOrder = -1000
)

func (item SortOrder) String() string {
	switch item {
	case SortOrderasc:
		return "asc"
	case SortOrderdesc:
		return "desc"
	default:
		return "Unknown"
	}
}

func (item SortOrder) Message() string {
	switch item {
	case SortOrderasc:
		return "升序"
	case SortOrderdesc:
		return "降序"
	default:
		return "Unknown"
	}
}

func ParseSortOrderFromString(msg string) SortOrder {
	switch msg {
	case "asc":
		return SortOrderasc
	case "desc":
		return SortOrderdesc
	default:
		return SortOrderUnknown
	}
}

func SortOrderValueEnum() map[string]any {
	return map[string]any{
		"asc":  "升序",
		"desc": "降序",
	}
}
