// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type ActionMeta struct {
	Name    string           `json:"name" query:"name" form:"name"`
	Columns []ResourceColumn `json:"columns" query:"columns" form:"columns"`
	Batch   bool             `json:"batch" query:"batch" form:"batch"`
}
