// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import ()

type AdminItem struct {
	Id        int64  `title:"标识" json:"id" query:"id" form:"id"`
	Username  string `title:"账号" json:"username" query:"username" form:"username"`
	Nickname  string `title:"昵称" json:"nickname" query:"nickname" form:"nickname"`
	Avatar    string `valueType:"image" title:"头像" json:"avatar" query:"avatar" form:"avatar"`
	Phone     string `title:"手机号" json:"phone" query:"phone" form:"phone"`
	Email     string `title:"邮箱" json:"email" query:"email" form:"email"`
	Role      string `valueType:"select" title:"角色" json:"role" query:"role" form:"role"`
	CreatedAt string `valueType:"dateTime" title:"创建时间" json:"created_at" query:"created_at" form:"created_at"`
	UpdatedAt string `valueType:"dateTime" title:"更新时间" hideInSearch:"true" hideInTable:"true" json:"updated_at" query:"updated_at" form:"updated_at"`
}
