// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type ForeignKey struct {
	Model      string `json:"model" query:"model" form:"model"`
	KeyField   string `json:"keyField" query:"keyField" form:"keyField"`
	LabelField string `json:"labelField" query:"labelField" form:"labelField"`
	Multiple   bool   `json:"multiple" query:"multiple" form:"multiple"`
	ForeignKey string `json:"foreignKey" query:"foreignKey" form:"foreignKey"`
}
