// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/menu.proto
// 
package admin

import ()

type Menu struct {
	Name       string  `json:"name" query:"name" form:"name"`
	Path       string  `json:"path" query:"path" form:"path"`
	Icon       string  `json:"icon" query:"icon" form:"icon"`
	HideInMenu bool    `json:"hideInMenu" query:"hideInMenu" form:"hideInMenu"`
	Access     string  `json:"access" query:"access" form:"access"`
	Children   []*Menu `json:"children" query:"children" form:"children"`
}
