// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type QueryParam struct {
	Key      string `json:"key" query:"key" form:"key"`
	Value    any    `json:"value" query:"value" form:"value"`
	Operator string `json:"operator" query:"operator" form:"operator"`
}
