// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type QueryParams struct {
	Page     int64        `json:"page" query:"page" form:"page"`
	PageSize int64        `json:"pageSize" query:"pageSize" form:"pageSize"`
	Sorters  []Sorter     `json:"sorters" query:"sorters" form:"sorters"`
	Params   []QueryParam `json:"params" query:"params" form:"params"`
	Keyword  string       `json:"keyword" query:"keyword" form:"keyword"`
}
