// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type ResourceMeta struct {
	Title      string           `json:"title" query:"title" form:"title"`
	Name       string           `json:"name" query:"name" form:"name"`
	Columns    []ResourceColumn `json:"columns" query:"columns" form:"columns"`
	RowKey     string           `json:"rowKey" query:"rowKey" form:"rowKey"`
	Exportable bool             `json:"exportable" query:"exportable" form:"exportable"`
	Deleteable bool             `json:"deleteable" query:"deleteable" form:"deleteable"`
	Creatable  bool             `json:"creatable" query:"creatable" form:"creatable"`
	Updatable  bool             `json:"updatable" query:"updatable" form:"updatable"`
	Copyable   bool             `json:"copyable" query:"copyable" form:"copyable"`
	Actions    []ActionMeta     `json:"actions" query:"actions" form:"actions"`
}
