// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type ResourceColumn struct {
	Title        string           `json:"title" query:"title" form:"title"`
	DataIndex    string           `json:"dataIndex" query:"dataIndex" form:"dataIndex"`
	ValueType    string           `json:"valueType" query:"valueType" form:"valueType"`
	Width        int32            `json:"width" query:"width" form:"width"`
	HideInSearch bool             `json:"hideInSearch" query:"hideInSearch" form:"hideInSearch"`
	HideInTable  bool             `json:"hideInTable" query:"hideInTable" form:"hideInTable"`
	Sorter       bool             `json:"sorter" query:"sorter" form:"sorter"`
	ValueEnum    any              `json:"valueEnum" query:"valueEnum" form:"valueEnum"`
	ForeignKey   *ForeignKey      `json:"foreignKey" query:"foreignKey" form:"foreignKey"`
	Columns      []ResourceColumn `json:"columns" query:"columns" form:"columns"`
	HideInForm   bool             `json:"hideInForm" query:"hideInForm" form:"hideInForm"`
	InitialValue any              `json:"initialValue" query:"initialValue" form:"initialValue"`
	Multiple     bool             `json:"multiple" query:"multiple" form:"multiple"`
	Order        int64            `json:"order" query:"order" form:"order"`
}
