// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 18:09:13
// source: pro/site.proto
// 
package admin

import ()

type SiteConfig struct {
	Title  string `json:"title" query:"title" form:"title"`
	Logo   string `json:"logo" query:"logo" form:"logo"`
	Footer string `json:"footer" query:"footer" form:"footer"`
}
