// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import ()

type Sorter struct {
	Field string `json:"field" query:"field" form:"field"`
	Order string `json:"order" query:"order" form:"order"`
}
