// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type BatchFetchFieldsReq struct {
	Model      string   `json:"model" query:"model" form:"model"`
	Keys       []string `json:"keys" query:"keys" form:"keys"`
	KeyField   string   `json:"keyField" query:"keyField" form:"keyField"`
	LabelField string   `json:"labelField" query:"labelField" form:"labelField"`
}

func (model *BatchFetchFieldsReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"model":      model.Model,
		"keys":       model.Keys,
		"keyField":   model.KeyField,
		"labelField": model.LabelField,
	}
	return fields
}
