// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type CreateAdminReq struct {
	Username string `json:"username" query:"username" form:"username"`
	Nickname string `json:"nickname" query:"nickname" form:"nickname"`
	Avatar   string `json:"avatar" query:"avatar" form:"avatar"`
	Phone    string `json:"phone" query:"phone" form:"phone"`
	Email    string `json:"email" query:"email" form:"email"`
	Role     string `json:"role" query:"role" form:"role"`
	Password string `json:"password" query:"password" form:"password"`
}

func (model *CreateAdminReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"username": model.Username,
		"nickname": model.Nickname,
		"avatar":   model.Avatar,
		"phone":    model.Phone,
		"email":    model.Email,
		"role":     model.Role,
		"password": model.Password,
	}
	return fields
}
