// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type DeleteAdminReq struct {
	Id int64 `json:"id" query:"id" form:"id"`
}

func (model *DeleteAdminReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"id": model.Id,
	}
	return fields
}
