// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type ListAdminsReq struct {
	Current  int32  `json:"current" query:"current" form:"current"`
	PageSize int32  `json:"page_size" query:"page_size" form:"page_size"`
	Username string `json:"username" query:"username" form:"username"`
	Nickname string `json:"nickname" query:"nickname" form:"nickname"`
	Phone    string `json:"phone" query:"phone" form:"phone"`
	Email    string `json:"email" query:"email" form:"email"`
}

func (model *ListAdminsReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"current":   model.Current,
		"page_size": model.PageSize,
		"username":  model.Username,
		"nickname":  model.Nickname,
		"phone":     model.Phone,
		"email":     model.Email,
	}
	return fields
}
