// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/models/admin"
)

type ListResourceReq struct {
	Model string            `json:"model" query:"model" form:"model"`
	Query admin.QueryParams `json:"query" query:"query" form:"query"`
}

func (model *ListResourceReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"model": model.Model,
		"query": model.Query,
	}
	return fields
}
