// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type LoginReq struct {
	Username string `json:"username" query:"username" form:"username"`
	Password string `json:"password" query:"password" form:"password"`
	Phone    string `json:"phone" query:"phone" form:"phone"`
	Code     string `json:"code" query:"code" form:"code"`
}

func (model *LoginReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"username": model.Username,
		"password": model.Password,
		"phone":    model.Phone,
		"code":     model.Code,
	}
	return fields
}
