// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type ResetPasswordReq struct {
	Phone       string `json:"phone" query:"phone" form:"phone"`
	Code        string `json:"code" query:"code" form:"code"`
	NewPassword string `json:"new_password" query:"new_password" form:"new_password"`
}

func (model *ResetPasswordReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"phone":        model.Phone,
		"code":         model.Code,
		"new_password": model.NewPassword,
	}
	return fields
}
