// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type ResourceActionReq struct {
	Model   string `json:"model" query:"model" form:"model"`
	Action  string `json:"action" query:"action" form:"action"`
	Payload string `json:"payload" query:"payload" form:"payload"`
}

func (model *ResourceActionReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"model":   model.Model,
		"action":  model.Action,
		"payload": model.Payload,
	}
	return fields
}
