// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
)

type SendSmsReq struct {
	Phone       string `json:"phone" query:"phone" form:"phone"`
	Type        string `json:"type" query:"type" form:"type"`
	CaptchaId   string `json:"captcha_id" query:"captcha_id" form:"captcha_id"`
	CaptchaCode string `json:"captcha_code" query:"captcha_code" form:"captcha_code"`
}

func (model *SendSmsReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"phone":        model.Phone,
		"type":         model.Type,
		"captcha_id":   model.CaptchaId,
		"captcha_code": model.CaptchaCode,
	}
	return fields
}
