// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	"github.com/goal-web/validation"
	admin "github.com/qbhy/goal-admin/requests/admin"
	"github.com/qbhy/goal-admin/response"
	svc "github.com/qbhy/goal-admin/services/admin"
)

func AdminManageServiceRouter(router contracts.HttpRouter) {
	routeGroup := router.Group("/api/admin", "auth:admin_jwt")
	routeGroup.GET("/admins", AdminManageServiceListAdmins)
	routeGroup.POST("/admin/delete", AdminManageServiceDeleteAdmin)
	routeGroup.POST("/admin/create", AdminManageServiceCreateAdmin)
	routeGroup.POST("/admin/update", AdminManageServiceUpdateAdmin)
}
func AdminManageServiceListAdmins(request contracts.HttpRequest) any {
	var req admin.ListAdminsReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AdminManageServiceListAdmins(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AdminManageServiceDeleteAdmin(request contracts.HttpRequest) any {
	var req admin.DeleteAdminReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AdminManageServiceDeleteAdmin(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AdminManageServiceCreateAdmin(request contracts.HttpRequest) any {
	var req admin.CreateAdminReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AdminManageServiceCreateAdmin(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AdminManageServiceUpdateAdmin(request contracts.HttpRequest) any {
	var req admin.UpdateAdminReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AdminManageServiceUpdateAdmin(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
