// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	"github.com/goal-web/validation"
	admin "github.com/qbhy/goal-admin/requests/admin"
	"github.com/qbhy/goal-admin/response"
	svc "github.com/qbhy/goal-admin/services/admin"
)

func AuthServiceRouter(router contracts.HttpRouter) {
	routeGroup := router.Group("/api/admin")
	routeGroup.Post("/login", AuthServiceLogin)
	routeGroup.Post("/send-sms", AuthServiceSendSms)
	routeGroup.GET("/captcha", AuthServiceGetCaptcha)
	routeGroup.Post("/reset-password", AuthServiceResetPassword)
	routeGroup.GET("/current-user", AuthServiceGetCurrentUser, "auth:admin_jwt")
}
func AuthServiceLogin(request contracts.HttpRequest) any {
	var req admin.LoginReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AuthServiceLogin(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AuthServiceSendSms(request contracts.HttpRequest) any {
	var req admin.SendSmsReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AuthServiceSendSms(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AuthServiceGetCaptcha(request contracts.HttpRequest) any {
	var req admin.GetCaptchaReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AuthServiceGetCaptcha(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AuthServiceResetPassword(request contracts.HttpRequest) any {
	var req admin.ResetPasswordReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AuthServiceResetPassword(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func AuthServiceGetCurrentUser(request contracts.HttpRequest) any {
	var req admin.GetCurrentUserReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.AuthServiceGetCurrentUser(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
