// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	"github.com/goal-web/validation"
	admin "github.com/qbhy/goal-admin/requests/admin"
	"github.com/qbhy/goal-admin/response"
	svc "github.com/qbhy/goal-admin/services/admin"
)

func ResourceServiceRouter(router contracts.HttpRouter) {
	routeGroup := router.Group("/api/admin", "auth:admin_jwt")
	routeGroup.GET("/resource/meta", ResourceServiceGetResourceMeta)
	routeGroup.POST("/resource/list", ResourceServiceListResource)
	routeGroup.GET("/resource/detail", ResourceServiceGetResourceDetail)
	routeGroup.POST("/resource/create", ResourceServiceCreateResource)
	routeGroup.POST("/resource/update", ResourceServiceUpdateResource)
	routeGroup.POST("/resource/delete", ResourceServiceDeleteResource)
	routeGroup.POST("/resource/batch-delete", ResourceServiceBatchDeleteResource)
	routeGroup.POST("/resource/export", ResourceServiceExportResource)
	routeGroup.POST("/resource/batch-fetch-fields", ResourceServiceBatchFetchFields)
	routeGroup.POST("/resource/action", ResourceServiceResourceAction)
}
func ResourceServiceGetResourceMeta(request contracts.HttpRequest) any {
	var req admin.GetResourceMetaReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceGetResourceMeta(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceListResource(request contracts.HttpRequest) any {
	var req admin.ListResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceListResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceGetResourceDetail(request contracts.HttpRequest) any {
	var req admin.GetResourceDetailReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceGetResourceDetail(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceCreateResource(request contracts.HttpRequest) any {
	var req admin.CreateResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceCreateResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceUpdateResource(request contracts.HttpRequest) any {
	var req admin.UpdateResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceUpdateResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceDeleteResource(request contracts.HttpRequest) any {
	var req admin.DeleteResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceDeleteResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceBatchDeleteResource(request contracts.HttpRequest) any {
	var req admin.BatchDeleteResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceBatchDeleteResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceExportResource(request contracts.HttpRequest) any {
	var req admin.ExportResourceReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceExportResource(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceBatchFetchFields(request contracts.HttpRequest) any {
	var req admin.BatchFetchFieldsReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceBatchFetchFields(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ResourceServiceResourceAction(request contracts.HttpRequest) any {
	var req admin.ResourceActionReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ResourceServiceResourceAction(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
