// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/site.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	"github.com/goal-web/validation"
	admin "github.com/qbhy/goal-admin/requests/admin"
	"github.com/qbhy/goal-admin/response"
	svc "github.com/qbhy/goal-admin/services/admin"
)

func SiteServiceRouter(router contracts.HttpRouter) {
	routeGroup := router.Group("/api/admin")
	routeGroup.GET("/site", SiteServiceGetSiteConfig)
}
func SiteServiceGetSiteConfig(request contracts.HttpRequest) any {
	var req admin.GetSiteConfigReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.SiteServiceGetSiteConfig(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
