// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin_manage.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/requests/admin"
	admin0 "github.com/qbhy/goal-admin/results/admin"
)

var AdminManageServiceDefine AdminManageServiceStatic

type AdminManageServiceStatic struct {
	ListAdmins  func(req *admin.ListAdminsReq, ctx contracts.Context) (*admin0.ListAdminsResult, error)
	DeleteAdmin func(req *admin.DeleteAdminReq, ctx contracts.Context) (*admin0.DeleteAdminResult, error)
	CreateAdmin func(req *admin.CreateAdminReq, ctx contracts.Context) (*admin0.CreateAdminResult, error)
	UpdateAdmin func(req *admin.UpdateAdminReq, ctx contracts.Context) (*admin0.UpdateAdminResult, error)
}

func AdminManageServiceListAdmins(req *admin.ListAdminsReq, ctx contracts.Context) (*admin0.ListAdminsResult, error) {
	if AdminManageServiceDefine.ListAdmins != nil {
		return AdminManageServiceDefine.ListAdmins(req, ctx)
	}
	return nil, nil
}

func AdminManageServiceDeleteAdmin(req *admin.DeleteAdminReq, ctx contracts.Context) (*admin0.DeleteAdminResult, error) {
	if AdminManageServiceDefine.DeleteAdmin != nil {
		return AdminManageServiceDefine.DeleteAdmin(req, ctx)
	}
	return nil, nil
}

func AdminManageServiceCreateAdmin(req *admin.CreateAdminReq, ctx contracts.Context) (*admin0.CreateAdminResult, error) {
	if AdminManageServiceDefine.CreateAdmin != nil {
		return AdminManageServiceDefine.CreateAdmin(req, ctx)
	}
	return nil, nil
}

func AdminManageServiceUpdateAdmin(req *admin.UpdateAdminReq, ctx contracts.Context) (*admin0.UpdateAdminResult, error) {
	if AdminManageServiceDefine.UpdateAdmin != nil {
		return AdminManageServiceDefine.UpdateAdmin(req, ctx)
	}
	return nil, nil
}
