// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/requests/admin"
	admin0 "github.com/qbhy/goal-admin/results/admin"
)

var AuthServiceDefine AuthServiceStatic

type AuthServiceStatic struct {
	Login          func(req *admin.LoginReq, ctx contracts.Context) (*admin0.LoginResult, error)
	SendSms        func(req *admin.SendSmsReq, ctx contracts.Context) (*admin0.SendSmsResult, error)
	GetCaptcha     func(req *admin.GetCaptchaReq, ctx contracts.Context) (*admin0.GetCaptchaResult, error)
	ResetPassword  func(req *admin.ResetPasswordReq, ctx contracts.Context) (*admin0.ResetPasswordResult, error)
	GetCurrentUser func(req *admin.GetCurrentUserReq, ctx contracts.Context) (*admin0.GetCurrentUserResult, error)
}

func AuthServiceLogin(req *admin.LoginReq, ctx contracts.Context) (*admin0.LoginResult, error) {
	if AuthServiceDefine.Login != nil {
		return AuthServiceDefine.Login(req, ctx)
	}
	return nil, nil
}

func AuthServiceSendSms(req *admin.SendSmsReq, ctx contracts.Context) (*admin0.SendSmsResult, error) {
	if AuthServiceDefine.SendSms != nil {
		return AuthServiceDefine.SendSms(req, ctx)
	}
	return nil, nil
}

func AuthServiceGetCaptcha(req *admin.GetCaptchaReq, ctx contracts.Context) (*admin0.GetCaptchaResult, error) {
	if AuthServiceDefine.GetCaptcha != nil {
		return AuthServiceDefine.GetCaptcha(req, ctx)
	}
	return nil, nil
}

func AuthServiceResetPassword(req *admin.ResetPasswordReq, ctx contracts.Context) (*admin0.ResetPasswordResult, error) {
	if AuthServiceDefine.ResetPassword != nil {
		return AuthServiceDefine.ResetPassword(req, ctx)
	}
	return nil, nil
}

func AuthServiceGetCurrentUser(req *admin.GetCurrentUserReq, ctx contracts.Context) (*admin0.GetCurrentUserResult, error) {
	if AuthServiceDefine.GetCurrentUser != nil {
		return AuthServiceDefine.GetCurrentUser(req, ctx)
	}
	return nil, nil
}
