// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/menu.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/requests/admin"
	admin0 "github.com/qbhy/goal-admin/results/admin"
)

var MenuServiceDefine MenuServiceStatic

type MenuServiceStatic struct {
	GetMenu func(req *admin.MenuListReq, ctx contracts.Context) (*admin0.MenuListResult, error)
}

func MenuServiceGetMenu(req *admin.MenuListReq, ctx contracts.Context) (*admin0.MenuListResult, error) {
	if MenuServiceDefine.GetMenu != nil {
		return MenuServiceDefine.GetMenu(req, ctx)
	}
	return nil, nil
}
