// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/resource.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/requests/admin"
	admin0 "github.com/qbhy/goal-admin/results/admin"
)

var ResourceServiceDefine ResourceServiceStatic

type ResourceServiceStatic struct {
	GetResourceMeta     func(req *admin.GetResourceMetaReq, ctx contracts.Context) (*admin0.GetResourceMetaResult, error)
	ListResource        func(req *admin.ListResourceReq, ctx contracts.Context) (*admin0.ListResourceResult, error)
	GetResourceDetail   func(req *admin.GetResourceDetailReq, ctx contracts.Context) (*admin0.GetResourceDetailResult, error)
	CreateResource      func(req *admin.CreateResourceReq, ctx contracts.Context) (*admin0.CreateResourceResult, error)
	UpdateResource      func(req *admin.UpdateResourceReq, ctx contracts.Context) (*admin0.UpdateResourceResult, error)
	DeleteResource      func(req *admin.DeleteResourceReq, ctx contracts.Context) (*admin0.DeleteResourceResult, error)
	BatchDeleteResource func(req *admin.BatchDeleteResourceReq, ctx contracts.Context) (*admin0.BatchDeleteResourceResult, error)
	ExportResource      func(req *admin.ExportResourceReq, ctx contracts.Context) (*admin0.ExportResourceResult, error)
	BatchFetchFields    func(req *admin.BatchFetchFieldsReq, ctx contracts.Context) (*admin0.BatchFetchFieldsResult, error)
	ResourceAction      func(req *admin.ResourceActionReq, ctx contracts.Context) (*admin0.ResourceActionResult, error)
}

func ResourceServiceGetResourceMeta(req *admin.GetResourceMetaReq, ctx contracts.Context) (*admin0.GetResourceMetaResult, error) {
	if ResourceServiceDefine.GetResourceMeta != nil {
		return ResourceServiceDefine.GetResourceMeta(req, ctx)
	}
	return nil, nil
}

func ResourceServiceListResource(req *admin.ListResourceReq, ctx contracts.Context) (*admin0.ListResourceResult, error) {
	if ResourceServiceDefine.ListResource != nil {
		return ResourceServiceDefine.ListResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceGetResourceDetail(req *admin.GetResourceDetailReq, ctx contracts.Context) (*admin0.GetResourceDetailResult, error) {
	if ResourceServiceDefine.GetResourceDetail != nil {
		return ResourceServiceDefine.GetResourceDetail(req, ctx)
	}
	return nil, nil
}

func ResourceServiceCreateResource(req *admin.CreateResourceReq, ctx contracts.Context) (*admin0.CreateResourceResult, error) {
	if ResourceServiceDefine.CreateResource != nil {
		return ResourceServiceDefine.CreateResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceUpdateResource(req *admin.UpdateResourceReq, ctx contracts.Context) (*admin0.UpdateResourceResult, error) {
	if ResourceServiceDefine.UpdateResource != nil {
		return ResourceServiceDefine.UpdateResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceDeleteResource(req *admin.DeleteResourceReq, ctx contracts.Context) (*admin0.DeleteResourceResult, error) {
	if ResourceServiceDefine.DeleteResource != nil {
		return ResourceServiceDefine.DeleteResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceBatchDeleteResource(req *admin.BatchDeleteResourceReq, ctx contracts.Context) (*admin0.BatchDeleteResourceResult, error) {
	if ResourceServiceDefine.BatchDeleteResource != nil {
		return ResourceServiceDefine.BatchDeleteResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceExportResource(req *admin.ExportResourceReq, ctx contracts.Context) (*admin0.ExportResourceResult, error) {
	if ResourceServiceDefine.ExportResource != nil {
		return ResourceServiceDefine.ExportResource(req, ctx)
	}
	return nil, nil
}

func ResourceServiceBatchFetchFields(req *admin.BatchFetchFieldsReq, ctx contracts.Context) (*admin0.BatchFetchFieldsResult, error) {
	if ResourceServiceDefine.BatchFetchFields != nil {
		return ResourceServiceDefine.BatchFetchFields(req, ctx)
	}
	return nil, nil
}

func ResourceServiceResourceAction(req *admin.ResourceActionReq, ctx contracts.Context) (*admin0.ResourceActionResult, error) {
	if ResourceServiceDefine.ResourceAction != nil {
		return ResourceServiceDefine.ResourceAction(req, ctx)
	}
	return nil, nil
}
