// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/site.proto
// 
package admin

import (
	"github.com/goal-web/contracts"
	admin "github.com/qbhy/goal-admin/requests/admin"
	admin0 "github.com/qbhy/goal-admin/results/admin"
)

var SiteServiceDefine SiteServiceStatic

type SiteServiceStatic struct {
	GetSiteConfig func(req *admin.GetSiteConfigReq, ctx contracts.Context) (*admin0.SiteConfigResult, error)
}

func SiteServiceGetSiteConfig(req *admin.GetSiteConfigReq, ctx contracts.Context) (*admin0.SiteConfigResult, error) {
	if SiteServiceDefine.GetSiteConfig != nil {
		return SiteServiceDefine.GetSiteConfig(req, ctx)
	}
	return nil, nil
}
