// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/admin.proto
// 
package models

import (
	"encoding/json"
	"fmt"
	"github.com/goal-web/collection"
	"github.com/goal-web/contracts"
	"github.com/goal-web/database/table"
	"github.com/goal-web/migration/migrate"
	"github.com/goal-web/supports/logs"
	"github.com/goal-web/supports/utils"
	"github.com/spf13/cast"
)

var ()

// AdminModel
// 管理员模型
// @authenticatable
// @timestamps
type AdminModel struct {
	//@goTag:title:"标识"
	Id int64 `title:"标识" json:"id" query:"id" form:"id" db:"id;type:BIGINT;not null;primary key;AUTO_INCREMENT;"`
	//@unique
	//@goTag:db:"username;type:varchar(32)" title:"账号"
	Username string `db:"username;type:varchar(32)" title:"账号" json:"username" query:"username" form:"username"`
	//@goTag:title:"昵称"
	Nickname string `title:"昵称" json:"nickname" query:"nickname" form:"nickname" db:"nickname;type:VARCHAR(255);not null;"`
	//@goTag:valueType:"image" title:"头像"
	Avatar string `valueType:"image" title:"头像" json:"avatar" query:"avatar" form:"avatar" db:"avatar;type:VARCHAR(255);not null;"`
	//@index
	//@goTag:db:"email;type:varchar(60)" title:"邮箱"
	Email string `db:"email;type:varchar(60)" title:"邮箱" json:"email" query:"email" form:"email"`
	//@unique
	//@goTag:db:"phone;type:varchar(11)" title:"手机号"
	Phone string `db:"phone;type:varchar(11)" title:"手机号" json:"phone" query:"phone" form:"phone"`
	//@index
	//@goTag:db:"role;type:varchar(20)" valueType:"select" valueEnum:"super:超级管理员;admin:管理员;viewer:查看者;" title:"角色"
	Role string `db:"role;type:varchar(20)" valueType:"select" valueEnum:"super:超级管理员;admin:管理员;viewer:查看者;" title:"角色" json:"role" query:"role" form:"role"`
	//@hidden
	//@goTag:valueType:"password" title:"密码" hideInTable:"true" hideInSearch:"true"
	Password string `valueType:"password" title:"密码" hideInTable:"true" hideInSearch:"true" json:"password" query:"password" form:"password" db:"password;type:VARCHAR(255);not null;"`
	//@goTag:valueType:"dateTime" title:"创建时间"  sorter:"true"
	CreatedAt string `valueType:"dateTime" title:"创建时间"  sorter:"true" json:"created_at" query:"created_at" form:"created_at" db:"created_at;type:timestamp;default CURRENT_TIMESTAMP;"`
	//@goTag:valueType:"dateTime" title:"更新时间" hideInSearch:"true" sorter:"true" hideInTable:"true"
	UpdatedAt string `valueType:"dateTime" title:"更新时间" hideInSearch:"true" sorter:"true" hideInTable:"true" json:"updated_at" query:"updated_at" form:"updated_at" db:"updated_at;type:timestamp;DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;"`

	_raw    contracts.Fields
	_update contracts.Fields
	_append contracts.Fields
	_hidden map[string]struct{}

	_relation_loaded map[contracts.RelationType]struct{}
}

var AdminDefine AdminStatic

type AdminStatic struct {
	TableName       string
	Hidden          []string
	Indexes         []string
	With            []contracts.RelationType
	Appends         map[string]func(model *AdminModel) any
	IdGetter        func(model *AdminModel, raw int64) int64
	IdSetter        func(model *AdminModel, raw int64) int64
	UsernameGetter  func(model *AdminModel, raw string) string
	UsernameSetter  func(model *AdminModel, raw string) string
	NicknameGetter  func(model *AdminModel, raw string) string
	NicknameSetter  func(model *AdminModel, raw string) string
	AvatarGetter    func(model *AdminModel, raw string) string
	AvatarSetter    func(model *AdminModel, raw string) string
	EmailGetter     func(model *AdminModel, raw string) string
	EmailSetter     func(model *AdminModel, raw string) string
	PhoneGetter     func(model *AdminModel, raw string) string
	PhoneSetter     func(model *AdminModel, raw string) string
	RoleGetter      func(model *AdminModel, raw string) string
	RoleSetter      func(model *AdminModel, raw string) string
	PasswordGetter  func(model *AdminModel, raw string) string
	PasswordSetter  func(model *AdminModel, raw string) string
	CreatedAtGetter func(model *AdminModel, raw string) string
	CreatedAtSetter func(model *AdminModel, raw string) string
	UpdatedAtGetter func(model *AdminModel, raw string) string
	UpdatedAtSetter func(model *AdminModel, raw string) string

	Saving           func(model *AdminModel) contracts.Exception
	Saved            func(model *AdminModel)
	Updating         func(model *AdminModel, fields contracts.Fields) contracts.Exception
	Updated          func(model *AdminModel, fields contracts.Fields)
	Deleting         func(model *AdminModel) contracts.Exception
	Deleted          func(model *AdminModel)
	PrimaryKeyGetter func(model *AdminModel) any
}

func AdminMigrator() migrate.Migrator {
	return func(executor contracts.SqlExecutor) contracts.Exception {
		return migrate.Migrate(AdminDefine.TableName, AdminDefine.Indexes, AdminModel{}, executor)
	}
}

func init() {
	AdminDefine.TableName = "admins"
	AdminDefine.Appends = make(map[string]func(model *AdminModel) any)
	AdminDefine.Hidden = append(
		AdminDefine.Hidden,
		"password",
	)
	AdminDefine.Indexes = append(
		AdminDefine.Indexes,
		"index;email_idx;(email)",
		"index;role_idx;(role)",
	)
	AdminDefine.Indexes = append(
		AdminDefine.Indexes,
		"unique index;username_idx;(username)",
		"unique index;phone_idx;(phone)",
	)
}

func NewAdminModel(fields contracts.Fields) *AdminModel {
	var model = AdminModel{
		_raw: fields,
	}
	model.Set(fields)
	return &model
}

func AdminModelSingleRelationSetter[T any](key contracts.RelationType) func(item *AdminModel, value []any) {
	return func(item *AdminModel, values []any) {
		var value T
		if len(values) > 0 {
			value = values[0].(T)
		}
		item.Set(contracts.Fields{
			string(key): value,
		})
	}
}
func AdminModelMultiRelationSetter[T any](key contracts.RelationType) func(item *AdminModel, value []any) {
	return func(model *AdminModel, value []any) {
		var results []T
		for _, item := range value {
			results = append(results, item.(T))
		}
		model.Set(contracts.Fields{string(key): results})
	}
}

func AdminModelLocalKeyGetter(key string) func(item *AdminModel) any {
	return func(item *AdminModel) any {
		return item.Get(key)
	}
}

func AdminModelRelationGetter[T any](query func() *table.Table[T], foreignKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		for key, values := range query().WhereIn(foreignKey, keys).Get().GroupBy(foreignKey) {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}

func AdminModelThroughRelationGetter[T any](query func() *table.Table[T], midTable, firstKey, secondKey, secondLocalKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		groupKey := fmt.Sprintf("%s.%s", midTable, firstKey)
		for key, values := range query().
			AddSelect(fmt.Sprintf("(%s) as _group_key", groupKey)).
			WhereIn(groupKey, keys).
			Join(midTable, fmt.Sprintf("%s.%s", midTable, secondLocalKey), "=", fmt.Sprintf("%s.%s", query().GetTableName(), secondKey)).
			Get().GroupBy("_group_key") {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}
func AdminQueryWithExecutor(executor contracts.SqlExecutor) *table.Table[AdminModel] {
	return AdminQuery().SetExecutor(executor)
}

func AdminQuery() *table.Table[AdminModel] {
	return table.NewQuery(AdminDefine.TableName, NewAdminModel).
		SetPrimaryKey("id").
		SetCreatedTimeColumn("created_at").
		SetUpdatedTimeColumn("updated_at").
		SetWiths(AdminDefine.With...)
}

func (model *AdminModel) Hidden(fields ...string) *AdminModel {
	for _, field := range fields {
		if model._hidden == nil {
			model._hidden = map[string]struct{}{
				field: struct{}{},
			}
		} else {
			model._hidden[field] = struct{}{}
		}

	}

	return model
}

func (model *AdminModel) Exists() bool {
	return AdminQuery().Where("id", model.GetPrimaryKey()).Count() > 0
}

func (model *AdminModel) Save() contracts.Exception {
	if model._update == nil {
		return nil
	}
	if AdminDefine.Saving != nil {
		if err := AdminDefine.Saving(model); err != nil {
			return err
		}
	}
	_, err := AdminQuery().Where("id", model.GetPrimaryKey()).UpdateE(model._update)
	if err == nil {
		model._update = nil
		if AdminDefine.Saved != nil {
			AdminDefine.Saved(model)
		}
	}

	return err
}

func (model *AdminModel) Set(fields contracts.Fields) {
	for key, value := range fields {

		switch key {
		case "id":
			switch v := value.(type) {
			case int64:
				model.SetId(v)
			case func() int64:
				model.SetId(v())
			case string:
				var vd int64
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			case []byte:
				var vd int64
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			default:
				model.SetId(cast.ToInt64(v))
			}
		case "username":
			switch v := value.(type) {
			case string:
				model.SetUsername(v)
			case func() string:
				model.SetUsername(v())
			case []byte:
				model.SetUsername(string(v))

			default:
				model.SetUsername(cast.ToString(v))
			}
		case "nickname":
			switch v := value.(type) {
			case string:
				model.SetNickname(v)
			case func() string:
				model.SetNickname(v())
			case []byte:
				model.SetNickname(string(v))

			default:
				model.SetNickname(cast.ToString(v))
			}
		case "avatar":
			switch v := value.(type) {
			case string:
				model.SetAvatar(v)
			case func() string:
				model.SetAvatar(v())
			case []byte:
				model.SetAvatar(string(v))

			default:
				model.SetAvatar(cast.ToString(v))
			}
		case "email":
			switch v := value.(type) {
			case string:
				model.SetEmail(v)
			case func() string:
				model.SetEmail(v())
			case []byte:
				model.SetEmail(string(v))

			default:
				model.SetEmail(cast.ToString(v))
			}
		case "phone":
			switch v := value.(type) {
			case string:
				model.SetPhone(v)
			case func() string:
				model.SetPhone(v())
			case []byte:
				model.SetPhone(string(v))

			default:
				model.SetPhone(cast.ToString(v))
			}
		case "role":
			switch v := value.(type) {
			case string:
				model.SetRole(v)
			case func() string:
				model.SetRole(v())
			case []byte:
				model.SetRole(string(v))

			default:
				model.SetRole(cast.ToString(v))
			}
		case "password":
			switch v := value.(type) {
			case string:
				model.SetPassword(v)
			case func() string:
				model.SetPassword(v())
			case []byte:
				model.SetPassword(string(v))

			default:
				model.SetPassword(cast.ToString(v))
			}
		case "created_at":
			switch v := value.(type) {
			case string:
				model.SetCreatedAt(v)
			case func() string:
				model.SetCreatedAt(v())
			case []byte:
				model.SetCreatedAt(string(v))

			default:
				model.SetCreatedAt(cast.ToString(v))
			}
		case "updated_at":
			switch v := value.(type) {
			case string:
				model.SetUpdatedAt(v)
			case func() string:
				model.SetUpdatedAt(v())
			case []byte:
				model.SetUpdatedAt(string(v))

			default:
				model.SetUpdatedAt(cast.ToString(v))
			}
		default:
			if model._append == nil {
				model._append = make(contracts.Fields)
			}
			model._append[key] = func() any {
				return value
			}
		}
	}
}

func (model *AdminModel) HasField(field string) bool {
	switch field {
	case "id", "username", "nickname", "avatar", "email", "phone", "role", "password", "created_at", "updated_at":
		return true
	default:
		return false
	}
}

func (model *AdminModel) Only(key ...string) contracts.Fields {
	var fields = make(contracts.Fields)
	for _, k := range key {
		if k == "id" {
			fields[k] = model.GetId()
			continue
		}
		if k == "username" {
			fields[k] = model.GetUsername()
			continue
		}
		if k == "nickname" {
			fields[k] = model.GetNickname()
			continue
		}
		if k == "avatar" {
			fields[k] = model.GetAvatar()
			continue
		}
		if k == "email" {
			fields[k] = model.GetEmail()
			continue
		}
		if k == "phone" {
			fields[k] = model.GetPhone()
			continue
		}
		if k == "role" {
			fields[k] = model.GetRole()
			continue
		}
		if k == "password" {
			fields[k] = model.GetPassword()
			continue
		}
		if k == "created_at" {
			fields[k] = model.GetCreatedAt()
			continue
		}
		if k == "updated_at" {
			fields[k] = model.GetUpdatedAt()
			continue
		}

		if AdminDefine.Appends[k] != nil {
			fields[k] = AdminDefine.Appends[k](model)
		}
	}
	return fields
}

func (model *AdminModel) Get(key string) any {
	switch key {
	case "id":
		return model.GetId()
	case "username":
		return model.GetUsername()
	case "nickname":
		return model.GetNickname()
	case "avatar":
		return model.GetAvatar()
	case "email":
		return model.GetEmail()
	case "phone":
		return model.GetPhone()
	case "role":
		return model.GetRole()
	case "password":
		return model.GetPassword()
	case "created_at":
		return model.GetCreatedAt()
	case "updated_at":
		return model.GetUpdatedAt()
	}

	if value, exists := model._append[key]; exists {
		return value
	}

	if fn, exists := AdminDefine.Appends[key]; exists {
		model._append[key] = fn(model)
		return model._append[key]
	}

	switch contracts.RelationType(key) {
	}

	return nil
}

func (model *AdminModel) Except(keys ...string) contracts.Fields {
	var excepts = map[string]struct{}{}
	for _, k := range keys {
		excepts[k] = struct{}{}
	}
	var fields = make(contracts.Fields)
	for key, value := range model.ToFields() {
		if _, ok := excepts[key]; ok {
			continue
		}
		fields[key] = value
	}
	return fields
}

func (model *AdminModel) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}

	model.Hidden(AdminDefine.Hidden...)

	fields := contracts.Fields{}
	if _, exists := model._hidden["id"]; !exists {
		fields["id"] = model.GetId()
	}
	if _, exists := model._hidden["username"]; !exists {
		fields["username"] = model.GetUsername()
	}
	if _, exists := model._hidden["nickname"]; !exists {
		fields["nickname"] = model.GetNickname()
	}
	if _, exists := model._hidden["avatar"]; !exists {
		fields["avatar"] = model.GetAvatar()
	}
	if _, exists := model._hidden["email"]; !exists {
		fields["email"] = model.GetEmail()
	}
	if _, exists := model._hidden["phone"]; !exists {
		fields["phone"] = model.GetPhone()
	}
	if _, exists := model._hidden["role"]; !exists {
		fields["role"] = model.GetRole()
	}
	if _, exists := model._hidden["password"]; !exists {
		fields["password"] = model.GetPassword()
	}
	if _, exists := model._hidden["created_at"]; !exists {
		fields["created_at"] = model.GetCreatedAt()
	}
	if _, exists := model._hidden["updated_at"]; !exists {
		fields["updated_at"] = model.GetUpdatedAt()
	}

	for key := range AdminDefine.Appends {
		value := model.Get(key)
		if fieldsProvider, ok := value.(contracts.FieldsProvider); ok {
			fields[key] = fieldsProvider.ToFields()
		} else {
			fields[key] = value
		}
	}

	for key := range model._relation_loaded {
		switch key {
		}
	}

	for key, value := range model._raw {
		_, hidden := model._hidden[key]
		if _, exists := fields[key]; !exists && !hidden {
			fields[key] = value
		}
	}

	return fields
}

func (model *AdminModel) Update(fields contracts.Fields) contracts.Exception {

	if AdminDefine.Updating != nil {
		if err := AdminDefine.Updating(model, fields); err != nil {
			return err
		}
	}

	if model._update != nil {
		utils.MergeFields(model._update, fields)
	}

	_, err := AdminQuery().Where("id", model.GetPrimaryKey()).UpdateE(fields)

	if err == nil {
		model.Set(fields)
		model._update = nil
		if AdminDefine.Updated != nil {
			AdminDefine.Updated(model, fields)
		}
	}

	return err
}

func (model *AdminModel) Refresh() contracts.Exception {
	fields, err := table.ArrayQuery("admins").Where("id", model.GetPrimaryKey()).FirstE()
	if err != nil {
		return err
	}

	model.Set(*fields)
	return nil
}

func (model *AdminModel) Delete() contracts.Exception {

	if AdminDefine.Deleting != nil {
		if err := AdminDefine.Deleting(model); err != nil {
			return err
		}
	}

	_, err := AdminQuery().Where("id", model.GetPrimaryKey()).DeleteE()
	if err == nil && AdminDefine.Deleted != nil {
		AdminDefine.Deleted(model)
	}

	return err
}

func (model *AdminModel) GetPrimaryKey() any {
	if AdminDefine.PrimaryKeyGetter != nil {
		return AdminDefine.PrimaryKeyGetter(model)
	}

	return model.Id
}
func (model *AdminModel) GetAuthenticatableKey() string {
	return fmt.Sprintf("%v", model.GetPrimaryKey())
}

func AdminAuthProvider(identify string) contracts.Authenticatable {
	return AdminQuery().Find(identify)
}

func (model *AdminModel) GetId() int64 {
	if AdminDefine.IdGetter != nil {
		return AdminDefine.IdGetter(model, model.Id)
	}
	return model.Id
}

func (model *AdminModel) SetId(value int64) {
	if AdminDefine.IdSetter != nil {
		value = AdminDefine.IdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"id": value}
	} else {
		model._update["id"] = value
	}
	model.Id = value
}

func (model *AdminModel) GetUsername() string {
	if AdminDefine.UsernameGetter != nil {
		return AdminDefine.UsernameGetter(model, model.Username)
	}
	return model.Username
}

func (model *AdminModel) SetUsername(value string) {
	if AdminDefine.UsernameSetter != nil {
		value = AdminDefine.UsernameSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"username": value}
	} else {
		model._update["username"] = value
	}
	model.Username = value
}

func (model *AdminModel) GetNickname() string {
	if AdminDefine.NicknameGetter != nil {
		return AdminDefine.NicknameGetter(model, model.Nickname)
	}
	return model.Nickname
}

func (model *AdminModel) SetNickname(value string) {
	if AdminDefine.NicknameSetter != nil {
		value = AdminDefine.NicknameSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"nickname": value}
	} else {
		model._update["nickname"] = value
	}
	model.Nickname = value
}

func (model *AdminModel) GetAvatar() string {
	if AdminDefine.AvatarGetter != nil {
		return AdminDefine.AvatarGetter(model, model.Avatar)
	}
	return model.Avatar
}

func (model *AdminModel) SetAvatar(value string) {
	if AdminDefine.AvatarSetter != nil {
		value = AdminDefine.AvatarSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"avatar": value}
	} else {
		model._update["avatar"] = value
	}
	model.Avatar = value
}

func (model *AdminModel) GetEmail() string {
	if AdminDefine.EmailGetter != nil {
		return AdminDefine.EmailGetter(model, model.Email)
	}
	return model.Email
}

func (model *AdminModel) SetEmail(value string) {
	if AdminDefine.EmailSetter != nil {
		value = AdminDefine.EmailSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"email": value}
	} else {
		model._update["email"] = value
	}
	model.Email = value
}

func (model *AdminModel) GetPhone() string {
	if AdminDefine.PhoneGetter != nil {
		return AdminDefine.PhoneGetter(model, model.Phone)
	}
	return model.Phone
}

func (model *AdminModel) SetPhone(value string) {
	if AdminDefine.PhoneSetter != nil {
		value = AdminDefine.PhoneSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"phone": value}
	} else {
		model._update["phone"] = value
	}
	model.Phone = value
}

func (model *AdminModel) GetRole() string {
	if AdminDefine.RoleGetter != nil {
		return AdminDefine.RoleGetter(model, model.Role)
	}
	return model.Role
}

func (model *AdminModel) SetRole(value string) {
	if AdminDefine.RoleSetter != nil {
		value = AdminDefine.RoleSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"role": value}
	} else {
		model._update["role"] = value
	}
	model.Role = value
}

func (model *AdminModel) GetPassword() string {
	if AdminDefine.PasswordGetter != nil {
		return AdminDefine.PasswordGetter(model, model.Password)
	}
	return model.Password
}

func (model *AdminModel) SetPassword(value string) {
	if AdminDefine.PasswordSetter != nil {
		value = AdminDefine.PasswordSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"password": value}
	} else {
		model._update["password"] = value
	}
	model.Password = value
}

func (model *AdminModel) GetCreatedAt() string {
	if AdminDefine.CreatedAtGetter != nil {
		return AdminDefine.CreatedAtGetter(model, model.CreatedAt)
	}
	return model.CreatedAt
}

func (model *AdminModel) SetCreatedAt(value string) {
	if AdminDefine.CreatedAtSetter != nil {
		value = AdminDefine.CreatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"created_at": value}
	} else {
		model._update["created_at"] = value
	}
	model.CreatedAt = value
}

func (model *AdminModel) GetUpdatedAt() string {
	if AdminDefine.UpdatedAtGetter != nil {
		return AdminDefine.UpdatedAtGetter(model, model.UpdatedAt)
	}
	return model.UpdatedAt
}

func (model *AdminModel) SetUpdatedAt(value string) {
	if AdminDefine.UpdatedAtSetter != nil {
		value = AdminDefine.UpdatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"updated_at": value}
	} else {
		model._update["updated_at"] = value
	}
	model.UpdatedAt = value
}
