// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.25.4
//
// updated_at: 2025-11-29 23:19:24
// source: pro/export.proto
// 
package models

import (
	"encoding/json"
	"fmt"
	"github.com/goal-web/collection"
	"github.com/goal-web/contracts"
	"github.com/goal-web/database/table"
	"github.com/goal-web/migration/migrate"
	"github.com/goal-web/supports/logs"
	"github.com/goal-web/supports/utils"
	admin "github.com/qbhy/goal-admin/models/admin"
	"github.com/spf13/cast"
)

var ()

// ExportModel
// 导出数据
// @timestamps
type ExportModel struct {
	//@goTag:title:"标识"
	Id int64 `title:"标识" json:"id" query:"id" form:"id" db:"id;type:BIGINT;not null;primary key;AUTO_INCREMENT;"`
	//@goTag:title:"管理员" hideInSearch:"true" hideInForm:"true" hideInTable:"true"
	AdminId uint64 `title:"管理员" hideInSearch:"true" hideInForm:"true" hideInTable:"true" json:"admin_id" query:"admin_id" form:"admin_id" db:"admin_id;type:BIGINT UNSIGNED;not null;"`
	//@goTag:valueType:"url" title:"下载地址" hideInSearch:"true"
	Url string `valueType:"url" title:"下载地址" hideInSearch:"true" json:"url" query:"url" form:"url" db:"url;type:VARCHAR(255);not null;"`
	//@goTag:valueType:"select" valueEnum:"pending:排队中,processing:处理中,completed:已完成,failed:处理失败" title:"状态"
	Status string `valueType:"select" valueEnum:"pending:排队中,processing:处理中,completed:已完成,failed:处理失败" title:"状态" json:"status" query:"status" form:"status" db:"status;type:VARCHAR(255);not null;"`
	//@goTag:title:"资源"
	Resource string `title:"资源" json:"resource" query:"resource" form:"resource" db:"resource;type:VARCHAR(255);not null;"`
	//@goTag:title:"参数" hideInTable:"true" hideInSearch:"true" hideInForm:"true"
	Params admin.QueryParams `title:"参数" hideInTable:"true" hideInSearch:"true" hideInForm:"true" json:"params" query:"params" form:"params" db:"params;type:json;not null;"`
	//@goTag:valueType:"dateTime" title:"创建时间"
	CreatedAt string `valueType:"dateTime" title:"创建时间" json:"created_at" query:"created_at" form:"created_at" db:"created_at;type:timestamp;default CURRENT_TIMESTAMP;"`
	//@goTag:valueType:"dateTime" title:"更新时间" hideInSearch:"true" hideInTable:"true"
	UpdatedAt string `valueType:"dateTime" title:"更新时间" hideInSearch:"true" hideInTable:"true" json:"updated_at" query:"updated_at" form:"updated_at" db:"updated_at;type:timestamp;DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;"`

	_raw    contracts.Fields
	_update contracts.Fields
	_append contracts.Fields
	_hidden map[string]struct{}

	_relation_loaded map[contracts.RelationType]struct{}
}

var ExportDefine ExportStatic

type ExportStatic struct {
	TableName       string
	Hidden          []string
	Indexes         []string
	With            []contracts.RelationType
	Appends         map[string]func(model *ExportModel) any
	IdGetter        func(model *ExportModel, raw int64) int64
	IdSetter        func(model *ExportModel, raw int64) int64
	AdminIdGetter   func(model *ExportModel, raw uint64) uint64
	AdminIdSetter   func(model *ExportModel, raw uint64) uint64
	UrlGetter       func(model *ExportModel, raw string) string
	UrlSetter       func(model *ExportModel, raw string) string
	StatusGetter    func(model *ExportModel, raw string) string
	StatusSetter    func(model *ExportModel, raw string) string
	ResourceGetter  func(model *ExportModel, raw string) string
	ResourceSetter  func(model *ExportModel, raw string) string
	ParamsGetter    func(model *ExportModel, raw admin.QueryParams) admin.QueryParams
	ParamsSetter    func(model *ExportModel, raw admin.QueryParams) admin.QueryParams
	CreatedAtGetter func(model *ExportModel, raw string) string
	CreatedAtSetter func(model *ExportModel, raw string) string
	UpdatedAtGetter func(model *ExportModel, raw string) string
	UpdatedAtSetter func(model *ExportModel, raw string) string

	Saving           func(model *ExportModel) contracts.Exception
	Saved            func(model *ExportModel)
	Updating         func(model *ExportModel, fields contracts.Fields) contracts.Exception
	Updated          func(model *ExportModel, fields contracts.Fields)
	Deleting         func(model *ExportModel) contracts.Exception
	Deleted          func(model *ExportModel)
	PrimaryKeyGetter func(model *ExportModel) any
}

func ExportMigrator() migrate.Migrator {
	return func(executor contracts.SqlExecutor) contracts.Exception {
		return migrate.Migrate(ExportDefine.TableName, ExportDefine.Indexes, ExportModel{}, executor)
	}
}

func init() {
	ExportDefine.TableName = "exports"
	ExportDefine.Appends = make(map[string]func(model *ExportModel) any)
}

func NewExportModel(fields contracts.Fields) *ExportModel {
	var model = ExportModel{
		_raw: fields,
	}
	model.Set(fields)
	return &model
}

func ExportModelSingleRelationSetter[T any](key contracts.RelationType) func(item *ExportModel, value []any) {
	return func(item *ExportModel, values []any) {
		var value T
		if len(values) > 0 {
			value = values[0].(T)
		}
		item.Set(contracts.Fields{
			string(key): value,
		})
	}
}
func ExportModelMultiRelationSetter[T any](key contracts.RelationType) func(item *ExportModel, value []any) {
	return func(model *ExportModel, value []any) {
		var results []T
		for _, item := range value {
			results = append(results, item.(T))
		}
		model.Set(contracts.Fields{string(key): results})
	}
}

func ExportModelLocalKeyGetter(key string) func(item *ExportModel) any {
	return func(item *ExportModel) any {
		return item.Get(key)
	}
}

func ExportModelRelationGetter[T any](query func() *table.Table[T], foreignKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		for key, values := range query().WhereIn(foreignKey, keys).Get().GroupBy(foreignKey) {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}

func ExportModelThroughRelationGetter[T any](query func() *table.Table[T], midTable, firstKey, secondKey, secondLocalKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		groupKey := fmt.Sprintf("%s.%s", midTable, firstKey)
		for key, values := range query().
			AddSelect(fmt.Sprintf("(%s) as _group_key", groupKey)).
			WhereIn(groupKey, keys).
			Join(midTable, fmt.Sprintf("%s.%s", midTable, secondLocalKey), "=", fmt.Sprintf("%s.%s", query().GetTableName(), secondKey)).
			Get().GroupBy("_group_key") {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}
func ExportQueryWithExecutor(executor contracts.SqlExecutor) *table.Table[ExportModel] {
	return ExportQuery().SetExecutor(executor)
}

func ExportQuery() *table.Table[ExportModel] {
	return table.NewQuery(ExportDefine.TableName, NewExportModel).
		SetPrimaryKey("id").
		SetCreatedTimeColumn("created_at").
		SetUpdatedTimeColumn("updated_at").
		SetWiths(ExportDefine.With...)
}

func (model *ExportModel) Hidden(fields ...string) *ExportModel {
	for _, field := range fields {
		if model._hidden == nil {
			model._hidden = map[string]struct{}{
				field: struct{}{},
			}
		} else {
			model._hidden[field] = struct{}{}
		}

	}

	return model
}

func (model *ExportModel) Exists() bool {
	return ExportQuery().Where("id", model.GetPrimaryKey()).Count() > 0
}

func (model *ExportModel) Save() contracts.Exception {
	if model._update == nil {
		return nil
	}
	if ExportDefine.Saving != nil {
		if err := ExportDefine.Saving(model); err != nil {
			return err
		}
	}
	_, err := ExportQuery().Where("id", model.GetPrimaryKey()).UpdateE(model._update)
	if err == nil {
		model._update = nil
		if ExportDefine.Saved != nil {
			ExportDefine.Saved(model)
		}
	}

	return err
}

func (model *ExportModel) Set(fields contracts.Fields) {
	for key, value := range fields {

		switch key {
		case "id":
			switch v := value.(type) {
			case int64:
				model.SetId(v)
			case func() int64:
				model.SetId(v())
			case string:
				var vd int64
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			case []byte:
				var vd int64
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			default:
				model.SetId(cast.ToInt64(v))
			}
		case "admin_id":
			switch v := value.(type) {
			case uint64:
				model.SetAdminId(v)
			case func() uint64:
				model.SetAdminId(v())
			case string:
				var vd uint64
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetAdminId(vd)

			case []byte:
				var vd uint64
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetAdminId(vd)

			default:
				model.SetAdminId(cast.ToUint64(v))
			}
		case "url":
			switch v := value.(type) {
			case string:
				model.SetUrl(v)
			case func() string:
				model.SetUrl(v())
			case []byte:
				model.SetUrl(string(v))

			default:
				model.SetUrl(cast.ToString(v))
			}
		case "status":
			switch v := value.(type) {
			case string:
				model.SetStatus(v)
			case func() string:
				model.SetStatus(v())
			case []byte:
				model.SetStatus(string(v))

			default:
				model.SetStatus(cast.ToString(v))
			}
		case "resource":
			switch v := value.(type) {
			case string:
				model.SetResource(v)
			case func() string:
				model.SetResource(v())
			case []byte:
				model.SetResource(string(v))

			default:
				model.SetResource(cast.ToString(v))
			}
		case "params":
			switch v := value.(type) {
			case admin.QueryParams:
				model.SetParams(v)
			case func() admin.QueryParams:
				model.SetParams(v())
			case string:
				var vd admin.QueryParams
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetParams(vd)

			case []byte:
				var vd admin.QueryParams
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetParams(vd)

			}
		case "created_at":
			switch v := value.(type) {
			case string:
				model.SetCreatedAt(v)
			case func() string:
				model.SetCreatedAt(v())
			case []byte:
				model.SetCreatedAt(string(v))

			default:
				model.SetCreatedAt(cast.ToString(v))
			}
		case "updated_at":
			switch v := value.(type) {
			case string:
				model.SetUpdatedAt(v)
			case func() string:
				model.SetUpdatedAt(v())
			case []byte:
				model.SetUpdatedAt(string(v))

			default:
				model.SetUpdatedAt(cast.ToString(v))
			}
		default:
			if model._append == nil {
				model._append = make(contracts.Fields)
			}
			model._append[key] = func() any {
				return value
			}
		}
	}
}

func (model *ExportModel) HasField(field string) bool {
	switch field {
	case "id", "admin_id", "url", "status", "resource", "params", "created_at", "updated_at":
		return true
	default:
		return false
	}
}

func (model *ExportModel) Only(key ...string) contracts.Fields {
	var fields = make(contracts.Fields)
	for _, k := range key {
		if k == "id" {
			fields[k] = model.GetId()
			continue
		}
		if k == "admin_id" {
			fields[k] = model.GetAdminId()
			continue
		}
		if k == "url" {
			fields[k] = model.GetUrl()
			continue
		}
		if k == "status" {
			fields[k] = model.GetStatus()
			continue
		}
		if k == "resource" {
			fields[k] = model.GetResource()
			continue
		}
		if k == "params" {
			fields[k] = model.GetParams()
			continue
		}
		if k == "created_at" {
			fields[k] = model.GetCreatedAt()
			continue
		}
		if k == "updated_at" {
			fields[k] = model.GetUpdatedAt()
			continue
		}

		if ExportDefine.Appends[k] != nil {
			fields[k] = ExportDefine.Appends[k](model)
		}
	}
	return fields
}

func (model *ExportModel) Get(key string) any {
	switch key {
	case "id":
		return model.GetId()
	case "admin_id":
		return model.GetAdminId()
	case "url":
		return model.GetUrl()
	case "status":
		return model.GetStatus()
	case "resource":
		return model.GetResource()
	case "params":
		return model.GetParams()
	case "created_at":
		return model.GetCreatedAt()
	case "updated_at":
		return model.GetUpdatedAt()
	}

	if value, exists := model._append[key]; exists {
		return value
	}

	if fn, exists := ExportDefine.Appends[key]; exists {
		model._append[key] = fn(model)
		return model._append[key]
	}

	switch contracts.RelationType(key) {
	}

	return nil
}

func (model *ExportModel) Except(keys ...string) contracts.Fields {
	var excepts = map[string]struct{}{}
	for _, k := range keys {
		excepts[k] = struct{}{}
	}
	var fields = make(contracts.Fields)
	for key, value := range model.ToFields() {
		if _, ok := excepts[key]; ok {
			continue
		}
		fields[key] = value
	}
	return fields
}

func (model *ExportModel) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}

	model.Hidden(ExportDefine.Hidden...)

	fields := contracts.Fields{}
	if _, exists := model._hidden["id"]; !exists {
		fields["id"] = model.GetId()
	}
	if _, exists := model._hidden["admin_id"]; !exists {
		fields["admin_id"] = model.GetAdminId()
	}
	if _, exists := model._hidden["url"]; !exists {
		fields["url"] = model.GetUrl()
	}
	if _, exists := model._hidden["status"]; !exists {
		fields["status"] = model.GetStatus()
	}
	if _, exists := model._hidden["resource"]; !exists {
		fields["resource"] = model.GetResource()
	}
	if _, exists := model._hidden["params"]; !exists {
		fields["params"] = model.GetParams()
	}
	if _, exists := model._hidden["created_at"]; !exists {
		fields["created_at"] = model.GetCreatedAt()
	}
	if _, exists := model._hidden["updated_at"]; !exists {
		fields["updated_at"] = model.GetUpdatedAt()
	}

	for key := range ExportDefine.Appends {
		value := model.Get(key)
		if fieldsProvider, ok := value.(contracts.FieldsProvider); ok {
			fields[key] = fieldsProvider.ToFields()
		} else {
			fields[key] = value
		}
	}

	for key := range model._relation_loaded {
		switch key {
		}
	}

	for key, value := range model._raw {
		_, hidden := model._hidden[key]
		if _, exists := fields[key]; !exists && !hidden {
			fields[key] = value
		}
	}

	return fields
}

func (model *ExportModel) Update(fields contracts.Fields) contracts.Exception {

	if ExportDefine.Updating != nil {
		if err := ExportDefine.Updating(model, fields); err != nil {
			return err
		}
	}

	if model._update != nil {
		utils.MergeFields(model._update, fields)
	}

	_, err := ExportQuery().Where("id", model.GetPrimaryKey()).UpdateE(fields)

	if err == nil {
		model.Set(fields)
		model._update = nil
		if ExportDefine.Updated != nil {
			ExportDefine.Updated(model, fields)
		}
	}

	return err
}

func (model *ExportModel) Refresh() contracts.Exception {
	fields, err := table.ArrayQuery("exports").Where("id", model.GetPrimaryKey()).FirstE()
	if err != nil {
		return err
	}

	model.Set(*fields)
	return nil
}

func (model *ExportModel) Delete() contracts.Exception {

	if ExportDefine.Deleting != nil {
		if err := ExportDefine.Deleting(model); err != nil {
			return err
		}
	}

	_, err := ExportQuery().Where("id", model.GetPrimaryKey()).DeleteE()
	if err == nil && ExportDefine.Deleted != nil {
		ExportDefine.Deleted(model)
	}

	return err
}

func (model *ExportModel) GetPrimaryKey() any {
	if ExportDefine.PrimaryKeyGetter != nil {
		return ExportDefine.PrimaryKeyGetter(model)
	}

	return model.Id
}

func (model *ExportModel) GetId() int64 {
	if ExportDefine.IdGetter != nil {
		return ExportDefine.IdGetter(model, model.Id)
	}
	return model.Id
}

func (model *ExportModel) SetId(value int64) {
	if ExportDefine.IdSetter != nil {
		value = ExportDefine.IdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"id": value}
	} else {
		model._update["id"] = value
	}
	model.Id = value
}

func (model *ExportModel) GetAdminId() uint64 {
	if ExportDefine.AdminIdGetter != nil {
		return ExportDefine.AdminIdGetter(model, model.AdminId)
	}
	return model.AdminId
}

func (model *ExportModel) SetAdminId(value uint64) {
	if ExportDefine.AdminIdSetter != nil {
		value = ExportDefine.AdminIdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"admin_id": value}
	} else {
		model._update["admin_id"] = value
	}
	model.AdminId = value
}

func (model *ExportModel) GetUrl() string {
	if ExportDefine.UrlGetter != nil {
		return ExportDefine.UrlGetter(model, model.Url)
	}
	return model.Url
}

func (model *ExportModel) SetUrl(value string) {
	if ExportDefine.UrlSetter != nil {
		value = ExportDefine.UrlSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"url": value}
	} else {
		model._update["url"] = value
	}
	model.Url = value
}

func (model *ExportModel) GetStatus() string {
	if ExportDefine.StatusGetter != nil {
		return ExportDefine.StatusGetter(model, model.Status)
	}
	return model.Status
}

func (model *ExportModel) SetStatus(value string) {
	if ExportDefine.StatusSetter != nil {
		value = ExportDefine.StatusSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"status": value}
	} else {
		model._update["status"] = value
	}
	model.Status = value
}

func (model *ExportModel) GetResource() string {
	if ExportDefine.ResourceGetter != nil {
		return ExportDefine.ResourceGetter(model, model.Resource)
	}
	return model.Resource
}

func (model *ExportModel) SetResource(value string) {
	if ExportDefine.ResourceSetter != nil {
		value = ExportDefine.ResourceSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"resource": value}
	} else {
		model._update["resource"] = value
	}
	model.Resource = value
}

func (model *ExportModel) GetParams() admin.QueryParams {
	if ExportDefine.ParamsGetter != nil {
		return ExportDefine.ParamsGetter(model, model.Params)
	}
	return model.Params
}

func (model *ExportModel) SetParams(value admin.QueryParams) {
	if ExportDefine.ParamsSetter != nil {
		value = ExportDefine.ParamsSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"params": value}
	} else {
		model._update["params"] = value
	}
	model.Params = value
}

func (model *ExportModel) GetCreatedAt() string {
	if ExportDefine.CreatedAtGetter != nil {
		return ExportDefine.CreatedAtGetter(model, model.CreatedAt)
	}
	return model.CreatedAt
}

func (model *ExportModel) SetCreatedAt(value string) {
	if ExportDefine.CreatedAtSetter != nil {
		value = ExportDefine.CreatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"created_at": value}
	} else {
		model._update["created_at"] = value
	}
	model.CreatedAt = value
}

func (model *ExportModel) GetUpdatedAt() string {
	if ExportDefine.UpdatedAtGetter != nil {
		return ExportDefine.UpdatedAtGetter(model, model.UpdatedAt)
	}
	return model.UpdatedAt
}

func (model *ExportModel) SetUpdatedAt(value string) {
	if ExportDefine.UpdatedAtSetter != nil {
		value = ExportDefine.UpdatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"updated_at": value}
	} else {
		model._update["updated_at"] = value
	}
	model.UpdatedAt = value
}
